language: python
sudo: required
dist: xenial

python:
  - "3.7"
  - "3.6"
  - "3.5"

matrix:
  fast_finish: true

# command to install dependencies
install:
  - pip install -U pip
  - ROBOTPY_NO_DEPS=1 pip install -r travis-requirements.txt
  - pip install -r docs/requirements.txt
# command to run tests
script:
  - RUNCOVERAGE=1 wpilib/tests/run_tests.sh
  - make -C docs html

jobs:
  include:
  - stage: format-check
    python:
    - "3.6"
    install:
    - pip install black
    script:
    - black --check --diff .

  - stage: deploy-pypi
    if: tag IS present
    install: true
    script: cd hal-sim
    deploy:
    - provider: pypi
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      on:
        tags: true
  - stage: deploy-pypi
    if: tag IS present
    install: true
    script: cd hal-base
    deploy:
    - provider: pypi
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      on:
        tags: true
  - stage: deploy-pypi
    if: tag IS present
    install: true
    script: cd hal-roborio
    deploy:
    - provider: pypi
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      on:
        tags: true
  - stage: deploy-pypi
    install: true
    if: tag IS present
    script: cd wpilib
    deploy:
      provider: pypi
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      on:
        tags: true

  - stage: deploy-github
    if: tag IS present
    install: true
    script: devtools/build_installer.sh
    deploy:
    - provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      file_glob: true
      file: dist/robotpy-*.zip
      skip_cleanup: true
      on:
        tags: true

git:
  depth: 200
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never
